FROM chialab/php:8.4

WORKDIR /app

COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

RUN printf "upload_max_filesize=20M\npost_max_size=20M\nmemory_limit=512M\n" > /usr/local/etc/php/conf.d/uploads.ini

EXPOSE 8000

ENTRYPOINT ["entrypoint.sh"]
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
