services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      - MYSQL_DATABASE=appifylab_feed
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:9160T5gH8x7KFVKSVRdy5TM0A50N/HUfn6CFQNn41hw=
      - APP_URL=http://54.158.189.35:8000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=appifylab_feed
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile.prod
      args:
        - VITE_API_URL=http://54.158.189.35:8000
    ports:
      - "80:80"
    restart: always

volumes:
  mysql_data:
