services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:9160T5gH8x7KFVKSVRdy5TM0A50N/HUfn6CFQNn41hw=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=appifylab_feed
      - DB_USERNAME=user
      - DB_PASSWORD=password
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile.prod
      args:
        - VITE_API_URL=http://localhost:8000
    ports:
      - "80:80"
    restart: always
